apiVersion: v1
kind: Service
metadata:
  name: order-ingest
  namespace: cex-core
spec:
  selector:
    app: order-ingest
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
